/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiku_android_avplayer_dlna_ftd_FTDJniInterface */

#ifndef _Included_com_qiku_android_avplayer_dlna_FTDJniInterface
#define _Included_com_qiku_android_avplayer_dlna_FTDJniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiku_android_avplayer_dlna_ftd_FTDJniInterface
 * Method:    startFileTransmitDevice
 * Signature: (Ljava/lang/string;Ljava/lang/string;)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_android_avplayer_dlna_ftd_FTDJniInterface_startFileTransmitDevice
  (JNIEnv *env, jobject thiz, jstring name, jstring uuid);

/*
 * Class:     com_qiku_android_avplayer_dlna_ftd_FTDJniInterface
 * Method:    responseGenaEvent
 * Signature: (ILjava/lang/string;Ljava/lang/string;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiku_android_avplayer_dlna_ftd_FTDJniInterface_responseGenaEvent
  (JNIEnv *env, jobject thiz, jint cmd, jstring value, jstring data);

/*
 * Class:     com_qiku_android_avplayer_dlna_ftd_FTDJniInterface
 * Method:    stopFileTransmitDevice
 * Signature: (V)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_android_avplayer_dlna_ftd_FTDJniInterface_stopFileTransmitDevice
  (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
