/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiku_dlna_render_jni_RENDERJniInterface */

#ifndef _Included_com_qiku_dlna_render_jni_RENDERJniInterface
#define _Included_com_qiku_dlna_render_jni_RENDERJniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiku_dlna_dmr_jni_PlatinumJniProxy
 * Method:    startMediaRender
 * Signature: (Ljava/lang/string;Ljava/lang/string;)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmr_jni_PlatinumJniProxy_startMediaRender
  (JNIEnv *env, jobject thiz, jstring name, jstring uuid);

/*
 * Class:     com_qiku_dlna_dmr_jni_PlatinumJniProxy
 * Method:    responseGenaEvent
 * Signature: (ILjava/lang/string;Ljava/lang/string;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiku_dlna_dmr_jni_PlatinumJniProxy_responseGenaEvent
  (JNIEnv *env, jobject thiz, jint cmd, jstring value, jstring data);

/*
 * Class:     com_qiku_dlna_dmr_jni_PlatinumJniProxy
 * Method:    stopMediaRender
 * Signature: (V)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmr_jni_PlatinumJniProxy_stopMediaRender
  (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
