/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiku_dlna_dmc_jni_DMCJniInterface */

#ifndef _Included_com_qiku_dlna_dmc_jni_DMCJniInterface
#define _Included_com_qiku_dlna_dmc_jni_DMCJniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_init
  (JNIEnv *, jobject);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    scanDevice
 * Signature: (JLjava/lang/string;)I
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_scanDevice(JNIEnv *env, jobject thiz, jlong _self, jlong mx);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getDmsList
 * Signature: (J)[Ljava/lang/object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getDmsList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getDmrList
 * Signature: (J)[Ljava/lang/object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getDmrList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    setDms
 * Signature: (JLjava/lang/string;)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_setDms
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    setDmr
 * Signature: (JLjava/lang/string;)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_setDmr
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    entryDirectory
 * Signature: (JLjava/lang/string;)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_entryDirectory
  (JNIEnv *env, jobject thiz, jlong _self, jstring dir);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getItemList
 * Signature: (J)[Ljava/lang/object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getItemList
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getFileList
 * Signature: (JI)[Ljava/lang/object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getFileList
  (JNIEnv *env, jobject thiz, jlong _self, jint flags);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getPositionInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getPositionInfo
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getTransportInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getTransportInfo
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getVolume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getVolume
  (JNIEnv *env, jobject thiz, jlong _self);

/* qiku add */
/* add volumedb interface, linhuaji, 2014.07.01 */
/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    setVolume
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_setVolume
  (JNIEnv *env, jobject thiz, jlong _self, jint vol);
  
/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getVolumeDB
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getVolumeDB
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    setVolumeDB
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_setVolumeDB
  (JNIEnv *env, jobject thiz, jlong _self, jint voldb);

  
/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getVolumeDBRange
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getVolumeDBRange
  (JNIEnv *env, jobject thiz, jlong _self);
/* qiku end */

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    setVolume
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_setVolume
  (JNIEnv *env, jobject thiz, jlong _self, jint vol);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getMute
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getMute
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    getDownloadUri
 * Signature: (JLjava/lang/string;I)Ljava/lang/string;
 */
JNIEXPORT jstring JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_getDownloadUri
  (JNIEnv *env, jobject thiz, jlong _self, jstring uri, jint flags);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlPlay2
 * Signature: (JLjava/lang/string;I)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlPlay2
  (JNIEnv *env, jobject thiz, jlong _self, jstring uri, jint flags);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlPlay
 * Signature: (JLjava/lang/string;I)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlPlay
  (JNIEnv *env, jobject thiz, jlong _self, jstring uri, jint flags);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlPlayOnline
 * Signature: (JLjava/lang/string;Ljava/lang/string;I)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlPlayOnline
  (JNIEnv *env, jobject thiz, jlong _self, jstring uri, jstring title, jint flags);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlSeek
 * Signature: (JLjava/lang/string;)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlSeek
  (JNIEnv *env, jobject thiz, jlong _self, jstring relTime);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlPause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlPause
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlResume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlResume
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlStop
  (JNIEnv *env, jobject thiz, jlong _self);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    ctrlMute
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_ctrlMute
  (JNIEnv *env, jobject thiz, jlong _self, jboolean mute);

/*
 * Class:     com_qiku_dlna_dmc_jni_DMCJniInterface
 * Method:    uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dmc_jni_DMCJniInterface_uninit
  (JNIEnv *, jobject, jlong _self);

/**************************************************************************/
/******************************DMS Jni Interface******************************/
/**************************************************************************/

/*
 * Class:     com_qiku_dlna_dms_jni_DMSJniInterface
 * Method:    startServer
 * Signature: (Ljava/lang/string;Ljava/lang/string;Ljava/lang/string;)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dms_jni_DMSJniInterface_startServer
  (JNIEnv *env, jobject thiz, jstring dir, jstring name, jstring uuid);

/*
 * Class:     com_qiku_dlna_dms_jni_DMSJniInterface
 * Method:    stopServer
 * Signature: (V)I
 */
JNIEXPORT jint JNICALL Java_com_qiku_dlna_dms_jni_DMSJniInterface_stopServer
  (JNIEnv *env, jobject thiz);

/**************************************************************************/
/******************************DMS Jni Interface******************************/
/**************************************************************************/



#ifdef __cplusplus
}
#endif
#endif
